<script setup lang="ts">
import { computed,h,ref,watch } from 'vue'
import { NAlert,NButton,NCard,NDataTable,NFormItem,NInput,NModal,NPagination,NSelect,NSpace,NTag } from 'naive-ui'
import { api,exportCsv,type Page } from './api'
const props=defineProps<{project:number;canManage:boolean}>()
interface Dataset{id:number;name:string;code:string;active_release_id:number|null}
const rows=ref<Dataset[]>([]),q=ref(''),page=ref(1),total=ref(0),selected=ref<Dataset|null>(null),description=ref<Record<string,any>|null>(null),releases=ref<Record<string,any>[]>([]),release=ref<number|null>(null),columns=ref<string[]>([]),result=ref<Record<string,any>|null>(null),offset=ref(0),busy=ref(false),error=ref('')
const filterField=ref<string|null>(null),filterOp=ref('EQ'),filterValue=ref(''),sortField=ref<string|null>(null),direction=ref('ASC'),queryExample=ref(false),showPolicy=ref(false),members=ref<{identity_id:string;role:string}[]>([]),policies=ref<Record<string,any>[]>([]),policyIdentity=ref<string|null>(null),policyColumns=ref<string[]>([]),rowField=ref<string|null>(null),rowValue=ref('')
const route=()=>`/warehouse/projects/${props.project}/datasets/${selected.value?.id}`
const fields=computed(()=>description.value?.fields||[])
const fieldOptions=computed(()=>fields.value.map((f:any)=>({label:`${f.description||f.name} (${f.name})`,value:f.name})))
const listing=[{title:'数据集',key:'name',render:(r:Dataset)=>h(NButton,{text:true,type:'primary',onClick:()=>inspect(r)},()=>r.name)},{title:'编码',key:'code'},{title:'当前发布',key:'active_release_id'}]
const names:Record<string,string>={UNPUBLISHED:'尚未发布',STALE:'数据已过期',FRESH:'满足新鲜度要求',NOT_CONFIGURED:'新鲜度要求未配置',UNKNOWN:'新鲜度未知'}
let generation=0
async function load(){const current=++generation;busy.value=true;error.value='';try{const value=await api<Page<Dataset>>(`/warehouse/catalog/projects/${props.project}/datasets?q=${encodeURIComponent(q.value)}&limit=25&offset=${(page.value-1)*25}`);if(current===generation){rows.value=value.items;total.value=value.total}}catch(e){if(current===generation)error.value=(e as Error).message}finally{if(current===generation)busy.value=false}}
async function inspect(row:Dataset){selected.value=row;result.value=null;error.value='';offset.value=0;filterField.value=null;sortField.value=null;try{[description.value,releases.value]=await Promise.all([api<Record<string,any>>(route()+'/description'),api<Record<string,any>[]>(route()+'/releases')]);release.value=row.active_release_id;columns.value=fields.value.map((f:any)=>f.name)}catch(e){error.value=(e as Error).message}}
function request(){return {releaseId:release.value,columns:columns.value,limit:50,offset:offset.value,...(filterField.value?{filters:[{field:filterField.value,op:filterOp.value,...(filterOp.value==='IN'?{values:filterValue.value.split(',').map(v=>v.trim())}:{value:filterValue.value})}]}:{}),...(sortField.value?{sort:[{field:sortField.value,direction:direction.value}]}:{})}}
async function query(){busy.value=true;error.value='';try{result.value=await api(route()+'/query',request())}catch(e){error.value=(e as Error).message}finally{busy.value=false}}
async function exported(){busy.value=true;error.value='';try{await exportCsv(route()+'/export',request(),`${selected.value?.code}-release-${release.value}-page-${offset.value/50+1}.csv`)}catch(e){error.value=(e as Error).message}finally{busy.value=false}}
async function grant(){busy.value=true;error.value='';try{[members.value,policies.value]=await Promise.all([api<typeof members.value>(`/warehouse/projects/${props.project}/members`),api<Record<string,any>[]>(route()+'/policies')]);policyIdentity.value=null;policyColumns.value=[];rowField.value=null;rowValue.value='';showPolicy.value=true}catch(e){error.value=(e as Error).message}finally{busy.value=false}}
async function savePolicy(){busy.value=true;error.value='';try{const current=policies.value.find(p=>p.identity_id===policyIdentity.value);await api(route()+'/policy',{identity:policyIdentity.value,columns:policyColumns.value,rowEquals:rowField.value?{[rowField.value]:rowValue.value}:{},expectedRevision:current?.revision||0});showPolicy.value=false}catch(e){error.value=(e as Error).message}finally{busy.value=false}}
watch(policyIdentity,()=>{const policy=policies.value.find(p=>p.identity_id===policyIdentity.value);policyColumns.value=policy?.columns_json||[];const entries=Object.entries(policy?.row_equals||{});rowField.value=entries[0]?.[0]||null;rowValue.value=entries[0]?.[1]===undefined?'':String(entries[0][1])})
const example=computed(()=>`POST /api/v1/warehouse/projects/${props.project}/datasets/${selected.value?.id}/query\nAuthorization: Bearer <服务令牌>\nContent-Type: application/json\n\n${JSON.stringify(request(),null,2)}`)
watch(release,()=>{offset.value=0;result.value=null});watch(page,()=>void load());watch(()=>props.project,()=>{selected.value=null;page.value=1;void load()},{immediate:true})
</script>
<template>
  <n-alert v-if="error" type="error" class="gap">{{error}}</n-alert>
  <n-card v-if="!selected" title="数据服务目录"><n-space class="gap"><n-input v-model:value="q" placeholder="数据集名称" @keyup.enter="page=1;load()"/><n-button @click="page=1;load()">搜索</n-button></n-space><n-data-table :columns="listing" :data="rows" :loading="busy"/><n-pagination v-model:page="page" :item-count="total" :page-size="25" class="gap"/></n-card>
  <template v-else><n-space class="gap"><n-button @click="selected=null;load()">返回目录</n-button><n-button @click="inspect(selected)">刷新数据集信息</n-button><n-button v-if="canManage" @click="grant">配置行列授权</n-button><n-button @click="queryExample=true">调用示例</n-button></n-space><n-card :title="selected.name"><n-space><n-tag>{{selected.active_release_id?'已有发布版本':'尚未发布'}}</n-tag><n-tag>{{names[description?.freshness?.state]||'加载中'}}</n-tag><span>本轮任务：{{description?.freshness?.currentTask?.state}}</span></n-space><p>粒度：{{description?.grain||'暂无'}} · 数据截止：{{description?.freshness?.dataAsOf||'暂无'}} · 业务域：{{description?.domain||'暂无'}}</p><n-alert v-if="description?.queryAuthorized===false" type="warning" class="gap">你可以查看目录，需要负责人授予行列权限后才能查询。</n-alert><n-form-item label="固定发布版本"><n-select v-model:value="release" :options="releases.map(r=>({label:`发布 ${r.id} · 模型 ${r.model_version} · ${r.published_at}`,value:r.id}))"/></n-form-item><n-form-item label="查询字段"><n-select v-model:value="columns" multiple :options="fieldOptions"/></n-form-item><n-space><n-select v-model:value="filterField" clearable :options="fieldOptions" placeholder="可选筛选字段" style="width:200px"/><n-select v-model:value="filterOp" :options="[{label:'等于',value:'EQ'},{label:'不等于',value:'NE'},{label:'大于',value:'GT'},{label:'大于等于',value:'GTE'},{label:'小于',value:'LT'},{label:'小于等于',value:'LTE'},{label:'包含于集合',value:'IN'}]" style="width:140px"/><n-input v-model:value="filterValue" :placeholder="filterOp==='IN'?'逗号分隔多个值':'筛选值'" style="width:230px"/></n-space><n-space class="gap"><n-select v-model:value="sortField" clearable :options="fieldOptions" placeholder="可选排序字段" style="width:200px"/><n-select v-model:value="direction" :options="[{label:'升序',value:'ASC'},{label:'降序',value:'DESC'}]" style="width:120px"/><n-button type="primary" :loading="busy" :disabled="!release||!columns.length" @click="offset=0;query()">查询</n-button><n-button :disabled="!release||!columns.length" @click="exported">导出本页 CSV</n-button></n-space><template v-if="result"><p>发布 {{result.releaseId}} · 模型 {{result.modelVersion}} · 权限版本 {{result.policyRevision}} · 第 {{offset/50+1}} 页 · {{names[result.freshness?.state]}}</p><n-data-table :columns="result.columns.map((name:string)=>({title:name,key:name}))" :data="result.rows"/><n-space class="gap"><n-button :disabled="offset===0||busy" @click="offset-=50;query()">上一页</n-button><n-button :disabled="!result.hasMore||busy" @click="offset+=50;query()">下一页</n-button></n-space></template><h3>字段说明</h3><n-data-table :columns="[{title:'字段',key:'name'},{title:'类型',key:'type'},{title:'说明',key:'description'}]" :data="fields"/></n-card></template>
  <n-modal v-model:show="queryExample" preset="card" title="数据服务调用示例" style="width:min(800px,96vw)"><p>在项目设置创建服务身份，并为其授予所需行列权限。示例固定发布版本，可复用于查询及导出。</p><pre class="json-detail">{{example}}</pre></n-modal>
  <n-modal v-model:show="showPolicy" preset="card" title="行列授权" style="width:min(740px,96vw)"><n-alert v-if="error" type="error" class="gap">{{error}}</n-alert><n-form-item label="项目查看者 / 服务身份"><n-select v-model:value="policyIdentity" :options="members.filter(m=>m.role==='VIEWER').map(m=>({label:m.identity_id,value:m.identity_id}))"/></n-form-item><n-form-item label="允许查询字段"><n-select v-model:value="policyColumns" multiple :options="fieldOptions"/></n-form-item><n-form-item label="行范围（可选等值条件）"><n-space><n-select v-model:value="rowField" clearable :options="fieldOptions" placeholder="不选择表示所有行" style="width:220px"/><n-input v-model:value="rowValue" placeholder="字段等于此值"/></n-space></n-form-item><n-button type="primary" :loading="busy" :disabled="!policyIdentity||!policyColumns.length" @click="savePolicy">保存授权新版本</n-button></n-modal>
</template>
