<script setup lang="ts">
import { defineAsyncComponent,h,onMounted,onUnmounted,reactive,ref,watch,computed } from 'vue'
import { NAlert,NButton,NCard,NCheckbox,NDataTable,NFormItem,NInput,NInputNumber,NModal,NSelect,NSpace,NStep,NSteps,NTag,type DataTableColumns } from 'naive-ui'
import { api } from './api'
const props=defineProps<{project:number;instances:{id:number;name:string;code:string}[];canManage:boolean;canActivate:boolean}>()
const OperationBar=defineAsyncComponent(()=>import('./OperationBar.vue'))
const DeliveryPanel=defineAsyncComponent(()=>import('./DeliveryPanel.vue'))
const SqlIngestion=defineAsyncComponent(()=>import('./SqlIngestion.vue'))
interface Connection {revision:number;config?:Record<string,unknown>;id:number;name:string;code:string;kind:string;resource_id:number;active_version:number}
interface Channel {revision:number;source_id:number;name:string;code:string;lifecycle:string;active_version:number;connection_version?:number;plan_id?:number;plan_version?:number;probe_state?:string;config?:Record<string,any>;plan?:{trigger_time:string;start_date:string;historical_read:boolean;contract:{lateDays?:number}}}
interface Resource {id:number;name:string;kind:string;environment_code:string}
const changeVisible=ref(false),changeReason=ref(''),changeImpact=ref<Record<string,any>|null>(null),connectionVersionVisible=ref(false),connectionDescription=ref(''),connectionReason=ref('')
async function reviewChange(){if(!editingChannel.value){await create();return}busy.value=true;error.value='';try{changeImpact.value=props.canActivate?await api(`/warehouse/projects/${props.project}/ingestion-operations/impact/channel/${channel.value?.source_id}`):null;changeReason.value='';changeVisible.value=true}catch(e){error.value=(e as Error).message}finally{busy.value=false}}
async function reviewConnection(){if(!connection.value)return;try{changeImpact.value=await api(`/warehouse/projects/${props.project}/ingestion-operations/impact/connection/${connection.value.id}`);connectionDescription.value=String(connection.value.config?.description||'');connectionReason.value='';connectionVersionVisible.value=true}catch(e){error.value=(e as Error).message}}
async function saveConnectionVersion(){if(!connection.value)return;busy.value=true;error.value='';try{await api(`/warehouse/projects/${props.project}/connections/${connection.value.id}/versions`,{expectedVersion:connection.value.active_version,config:connection.value.kind==='MYSQL_SNAPSHOT'?connection.value.config:{description:connectionDescription.value},reason:connectionReason.value});connectionVersionVisible.value=false;await select(connection.value);await load()}catch(e){error.value=(e as Error).message}finally{busy.value=false}}
interface Probe {id:number;state:string;error_code?:string;result?:{fileCount?:number;tableCount?:number;firstPageRows?:number;fields?:string[];unsupportedCount?:number;inventory?:{tables:{table:string;engine:string}[];unsupported_objects:Record<string,unknown>[]}}}
const templateConfig=ref<Record<string,any>|null>(null)
const editingChannel=ref(false),checkedChannels=ref<number[]>([])
const operationTargets=computed(()=>channels.value.filter(c=>checkedChannels.value.includes(c.source_id)).map(c=>({type:'channel' as const,id:c.source_id,expectedVersion:c.revision})))
const instance=ref<number|null>(null),connections=ref<Connection[]>([]),connection=ref<Connection|null>(null),channels=ref<Channel[]>([]),resources=ref<Resource[]>([])
const error=ref(''),busy=ref(false),modal=ref(false),step=ref(1),channel=ref<Channel|null>(null),probe=ref<Probe|null>(null),sqlReady=ref(false)
const sqlMode=computed(()=>kind.value==='MYSQL_SNAPSHOT'&&form.sourceMode==='REGISTERED_SQL')
const day=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Shanghai'}).format(new Date())
const defaults=()=>({resourceId:null as number|null,connectionCode:'',connectionName:'',database:'',code:'',name:'',relativeDirectory:'',datePartitioned:true,mode:'DAILY_SET',readiness:'DONE',expectedFiles:'',allowEmpty:false,allowContentRevision:false,stableMs:120000,dueTime:'09:00',dueDayOffset:0,format:'csv',encoding:'utf-8-sig',delimiter:',',sheets:'',range:'',recordsPath:'',formulaPolicy:'cached',path:'',pagination:'none',apiRecordsPath:'',pageSize:100,maxPages:1000,nextPath:'',cursorParam:'cursor',successPath:'',successValue:'true',triggerTime:'08:00',startDate:day(),lateDays:7,historicalRead:false,connectionVersion:1,mysqlTables:'',sourceMode:'TABLE_LIST'})
const form=reactive(defaults())
const selectedResource=computed(()=>resources.value.find(r=>r.id===form.resourceId))
const kind=computed(()=>connection.value?.kind||selectedResource.value?.kind)
const labels:Record<string,string>={MYSQL_SNAPSHOT:'MySQL',FILE_SCAN:'文件目录',REST_PULL:'REST API'}
const stateLabels:Record<string,string>={DRAFT:'草稿',ACTIVE:'启用',PAUSED:'暂停',RETIRED:'退役',QUEUED:'等待执行',RUNNING:'检查中',COMPLETE:'检查通过',FAILED:'失败'}
let timer:ReturnType<typeof setTimeout>|undefined,epoch=0
const connectionColumns:DataTableColumns<Connection>=[{title:'连接',key:'name',render:row=>h(NButton,{text:true,type:'primary',onClick:()=>select(row)},()=>row.name)},{title:'类型',key:'kind',render:row=>labels[row.kind]},{title:'环境',key:'environment_code'},{title:'采集通道',key:'channel_count'}]
const channelColumns:DataTableColumns<Channel>=[{type:'selection'},{title:'通道',key:'name'},{title:'来源编码',key:'code'},{title:'登记状态',key:'lifecycle',render:row=>stateLabels[row.lifecycle]||row.lifecycle},{title:'最近预检',key:'probe_state',render:row=>stateLabels[row.probe_state||'']||'未检查'},{title:'操作',key:'actions',render:row=>h(NSpace,{},()=>[
  h(NButton,{size:'small',onClick:()=>resume(row)},()=>row.plan_id?'查看 / 调整':'继续配置'),
  h(NButton,{size:'small',onClick:()=>copyChannel(row)},()=> '复制为新通道'),
  ...(row.plan_id?[h(NButton,{size:'small',onClick:()=>trigger(row)},()=> '采集今日')]:[]),
])}]
async function load(){if(!instance.value)return;const current=++epoch;busy.value=true;error.value='';try{const result=await api<Connection[]>(`/warehouse/projects/${props.project}/instances/${instance.value}/connections`);if(current===epoch)connections.value=result}catch(e){error.value=(e as Error).message}finally{if(current===epoch)busy.value=false}}
async function select(row:Connection){try{connection.value=await api<Connection>(`/warehouse/projects/${props.project}/connections/${row.id}`);checkedChannels.value=[];channels.value=await api<Channel[]>(`/warehouse/projects/${props.project}/connections/${row.id}/channels`)}catch(e){error.value=(e as Error).message}}
async function open(newConnection=false){error.value='';if(newConnection)connection.value=null;resources.value=await api<Resource[]>(`/warehouse/projects/${props.project}/resources`);channel.value=null;templateConfig.value=null;editingChannel.value=false;probe.value=null;step.value=1;Object.assign(form,defaults());modal.value=true}
function settings(){if(kind.value==='MYSQL_SNAPSHOT'){if(form.sourceMode==='REGISTERED_SQL')return {sourceMode:'REGISTERED_SQL'};return form.mysqlTables.trim()?{tables:form.mysqlTables.split('\n').map(v=>v.trim()).filter(Boolean)}:{sourceMode:'TABLE_LIST'}}
  if(kind.value==='REST_PULL'){const result:Record<string,unknown>={...(channel.value?.config||templateConfig.value),path:form.path,pagination:{...(channel.value?.config||templateConfig.value)?.pagination,mode:form.pagination,records_path:form.apiRecordsPath,page_size:form.pageSize,max_pages:form.maxPages,...(['next','token'].includes(form.pagination)?{next_path:form.nextPath,cursor_param:form.cursorParam}:{})}};if(!form.successPath)delete result.success;if(form.successPath)result.success={path:form.successPath,equals:form.successValue==='true'?true:form.successValue==='false'?false:form.successValue};return result;}
  const parser:Record<string,unknown>={...(channel.value?.config||templateConfig.value)?.delivery?.parser};if(form.format==='csv'){parser.encoding=form.encoding;parser.delimiter=form.delimiter}if(form.format==='xlsx'){if(form.sheets)parser.sheets=form.sheets.split(',').map(v=>v.trim()).filter(Boolean);if(form.range)parser.range=form.range;parser.formulaPolicy=form.formulaPolicy}if(form.format==='json')parser.recordsPath=form.recordsPath;
  return {relativeDirectory:form.relativeDirectory,datePartitioned:form.datePartitioned,delivery:{...(channel.value?.config||templateConfig.value)?.delivery,version:1,mode:form.mode,readiness:form.readiness,stableMs:form.stableMs,expectedFiles:form.expectedFiles.split('\n').map(v=>v.trim()).filter(Boolean),allowEmpty:form.allowEmpty,allowContentRevision:form.allowContentRevision,dueTime:form.dueTime,dueDayOffset:form.dueDayOffset,parser}};
}
async function copyChannel(row:Channel){await resume(row);if(!channel.value)return;templateConfig.value=structuredClone(JSON.parse(JSON.stringify(channel.value.config||{})));channel.value=null;editingChannel.value=false;probe.value=null;step.value=1;form.code='';form.name=row.name+'副本';form.startDate=day()}
async function create(){busy.value=true;error.value='';try{if(!connection.value){const result=await api<Connection>(`/warehouse/projects/${props.project}/instances/${instance.value}/connections`,{code:form.connectionCode,name:form.connectionName,resourceId:form.resourceId,config:kind.value==='MYSQL_SNAPSHOT'?{database:form.database}:{}});connection.value=await api<Connection>(`/warehouse/projects/${props.project}/connections/${result.id}`)}
    if(!channel.value)channel.value=await api<Channel>(`/warehouse/projects/${props.project}/connections/${connection.value.id}/channels`,{code:form.code,name:form.name,config:settings()});else if(editingChannel.value){channel.value=await api<Channel>(`/warehouse/projects/${props.project}/channels/${channel.value.source_id}/versions`,{expectedVersion:channel.value.active_version,connectionVersion:form.connectionVersion,config:settings(),reason:changeReason.value});editingChannel.value=false}await testConnection();step.value=2;await load();
  }catch(e){error.value=(e as Error).message}finally{busy.value=false}}
async function testConnection(){if(!channel.value||sqlMode.value){probe.value=null;return}probe.value=await api<Probe>(`/warehouse/projects/${props.project}/channels/${channel.value.source_id}/probes`,{requestKey:crypto.randomUUID()});void poll()}
async function poll(){clearTimeout(timer);if(!channel.value||!modal.value)return;try{const all=await api<Probe[]>(`/warehouse/projects/${props.project}/channels/${channel.value.source_id}/probes`);const current=all.find(p=>p.id===probe.value?.id);if(current)probe.value=current;if(current&&['QUEUED','RUNNING'].includes(current.state))timer=setTimeout(()=>void poll(),1500)}catch(e){error.value=(e as Error).message}}
async function resume(row:Channel){try{channel.value=await api<Channel>(`/warehouse/projects/${props.project}/channels/${row.source_id}`);const ch=channel.value,c=ch.config||{},delivery=c.delivery||{},parser=delivery.parser||{};Object.assign(form,{connectionVersion:ch.connection_version||1,sourceMode:c.sourceMode==='REGISTERED_SQL'?'REGISTERED_SQL':'TABLE_LIST',mysqlTables:(c.tables||[]).join('\n'),code:ch.code,name:ch.name,relativeDirectory:c.relativeDirectory||'',datePartitioned:c.datePartitioned===true,mode:delivery.mode||'DAILY_SET',readiness:delivery.readiness||'DONE',expectedFiles:(delivery.expectedFiles||[]).join('\n'),allowEmpty:delivery.allowEmpty===true,allowContentRevision:delivery.allowContentRevision===true,dueTime:delivery.dueTime||'09:00',dueDayOffset:delivery.dueDayOffset||0,encoding:parser.encoding||'utf-8-sig',delimiter:parser.delimiter||',',sheets:(parser.sheets||[]).join(','),range:parser.range||'',recordsPath:parser.recordsPath||'',format:parser.sheets||parser.range?'xlsx':parser.recordsPath?'json':'csv',formulaPolicy:parser.formulaPolicy||'cached',path:c.path||'',pagination:c.pagination?.mode||'none',apiRecordsPath:c.pagination?.records_path||'',pageSize:c.pagination?.page_size||100,maxPages:c.pagination?.max_pages||1000,nextPath:c.pagination?.next_path||'',cursorParam:c.pagination?.cursor_param||'cursor',successPath:c.success?.path||'',successValue:String(c.success?.equals??true),triggerTime:ch.plan?.trigger_time?.slice(0,5)||'08:00',startDate:ch.plan?.start_date||day(),historicalRead:ch.plan?.historical_read||false,lateDays:ch.plan?.contract?.lateDays??7});probe.value=null;step.value=2;modal.value=true;const all=await api<Probe[]>(`/warehouse/projects/${props.project}/channels/${row.source_id}/probes`);probe.value=all.find(p=>(p as Probe&{channel_version:number}).channel_version===ch.active_version)||null;if(probe.value)void poll()}catch(e){error.value=(e as Error).message}}
async function activate(){if(!channel.value||(!probe.value&&!sqlMode.value))return;busy.value=true;error.value='';try{await api(`/warehouse/projects/${props.project}/channels/${channel.value.source_id}/activate`,{probeId:probe.value?.id??null,expectedPlanVersion:channel.value.plan_version||0,timezone:'Asia/Shanghai',triggerTime:form.triggerTime,startDate:form.startDate,lateDays:form.lateDays,historicalRead:kind.value==='MYSQL_SNAPSHOT'?false:form.historicalRead,maxAttempts:3,timeoutSeconds:3600});modal.value=false;if(connection.value)await select(connection.value)}catch(e){error.value=(e as Error).message}finally{busy.value=false}}
async function trigger(row:Channel){busy.value=true;error.value='';try{await api(`/warehouse/projects/${props.project}/channels/${row.source_id}/trigger`,{day:day(),reason:'工作台手动采集'});error.value='';if(connection.value)await select(connection.value)}catch(e){error.value=(e as Error).message}finally{busy.value=false}}
watch(instance,()=>{connection.value=null;channels.value=[];void load()});watch(()=>props.instances,items=>{if(!items.some(i=>i.id===instance.value))instance.value=items[0]?.id||null},{immediate:true});watch(modal,v=>{if(!v)clearTimeout(timer)});onUnmounted(()=>clearTimeout(timer));onMounted(()=>void load())
</script>
<template>
  <n-card title="连接与采集通道" class="gap">
    <n-alert v-if="error" type="error" class="gap">{{error}}</n-alert>
    <n-space class="gap"><n-select v-model:value="instance" :options="instances.map(i=>({label:i.name,value:i.id}))" placeholder="选择环境实例" style="width:220px"/><n-button v-if="instance&&canManage" @click="open(true)">接入新来源</n-button></n-space>
    <n-data-table :columns="connectionColumns" :data="connections" :loading="busy"/>
    <template v-if="connection"><OperationBar v-if="canActivate" :project="project" :targets="[{type:'connection',id:connection.id,expectedVersion:connection.revision}]" @changed="select(connection);load()"/><n-space class="gap"><strong>{{connection.name}} 的采集通道</strong><n-button v-if="canManage" @click="open()">复用连接新增通道</n-button><n-button v-if="canActivate" @click="reviewConnection">连接版本与影响</n-button></n-space><n-data-table v-model:checked-row-keys="checkedChannels" :row-key="r=>r.source_id" :columns="channelColumns" :data="channels"/><OperationBar v-if="canActivate" :project="project" :targets="operationTargets" @changed="select(connection)"/></template>
  </n-card>
  <DeliveryPanel v-if="instance" :project="project" :instance="instance" :can-manage="canActivate"/>
  <n-modal v-model:show="modal" preset="card" title="配置数据接入" style="width:min(800px,95vw)">
    <n-steps :current="step" class="gap"><n-step title="连接与采集规则"/><n-step title="测试与发现"/><n-step title="交付计划"/></n-steps>
    <n-alert v-if="error" type="error" class="gap">{{error}}</n-alert>
    <template v-if="step===1">
      <template v-if="!connection"><n-form-item label="已授权执行资源"><n-select v-model:value="form.resourceId" :options="resources.map(r=>({label:`${r.name} · ${labels[r.kind]} · ${r.environment_code}`,value:r.id}))"/></n-form-item><n-space><n-form-item label="连接编码"><n-input v-model:value="form.connectionCode"/></n-form-item><n-form-item label="连接名称"><n-input v-model:value="form.connectionName"/></n-form-item></n-space><n-form-item v-if="kind==='MYSQL_SNAPSHOT'" label="数据库名称"><n-input v-model:value="form.database" placeholder="须与已批准资源的数据库一致"/></n-form-item></template>
      <n-form-item v-if="editingChannel&&connection" label="显式使用连接版本"><n-select v-model:value="form.connectionVersion" :options="Array.from(new Set([form.connectionVersion,...Array.from({length:Math.min(200,connection.active_version)},(_,i)=>connection!.active_version-i)])).map(value=>({label:`连接版本 ${value}`,value}))"/></n-form-item><n-space><n-form-item label="来源稳定编码"><n-input v-model:value="form.code" placeholder="如 erp_test_orders"/></n-form-item><n-form-item label="采集通道名称"><n-input v-model:value="form.name"/></n-form-item></n-space>
      <n-alert v-if="kind==='MYSQL_SNAPSHOT'" type="info" class="gap">默认发现并接入整库基础表，共享一次数据库快照。视图和不支持的对象单独列示。</n-alert>
      <n-form-item v-if="kind==='MYSQL_SNAPSHOT'" label="来源模式"><n-select v-model:value="form.sourceMode" :options="[{label:'按表清单',value:'TABLE_LIST'},{label:'自定义 SQL（登记式）',value:'REGISTERED_SQL'}]" style="width:220px"/></n-form-item><n-alert v-if="sqlMode" type="info" class="gap">下一步进入 SQL 定义：编辑器、校验、必须成功预览一次，再保存并启用版本。</n-alert><n-form-item v-if="kind==='MYSQL_SNAPSHOT'&&!sqlMode" label="表范围（留空为整库，每行一张表）"><n-input v-model:value="form.mysqlTables" type="textarea" placeholder="留空：所有支持的基础表"/></n-form-item><template v-if="kind==='FILE_SCAN'">
        <n-form-item label="资源根目录下的相对目录"><n-input v-model:value="form.relativeDirectory" placeholder="留空使用已授权根目录"/></n-form-item><n-checkbox v-model:checked="form.datePartitioned">每日子目录（YYYY-MM-DD）</n-checkbox>
        <n-space class="gap"><n-form-item label="交付方式"><n-select v-model:value="form.mode" :options="[{label:'固定每日文件集',value:'DAILY_SET'},{label:'交付清单',value:'MANIFEST'},{label:'持续到达文件',value:'EVENT'}]" style="width:180px"/></n-form-item><n-form-item label="完成信号"><n-select v-model:value="form.readiness" :options="[{label:'.done 标记',value:'DONE'},{label:'文件稳定观察',value:'STABLE'}]" style="width:180px"/></n-form-item></n-space>
        <n-form-item v-if="form.mode==='DAILY_SET'" label="每日必需文件（每行一个相对文件名）"><n-input v-model:value="form.expectedFiles" type="textarea" placeholder="orders.csv&#10;customers.xlsx"/></n-form-item>
        <n-alert v-if="form.mode==='MANIFEST'" type="info">按交付清单约定提供 _delivery.json 及其 .done 标记。</n-alert>
        <n-form-item label="解析格式设置"><n-select v-model:value="form.format" :options="['csv','xlsx','json','parquet'].map(value=>({value,label:value.toUpperCase()}))"/></n-form-item>
        <n-space v-if="form.format==='csv'"><n-form-item label="编码"><n-select v-model:value="form.encoding" :options="['utf-8-sig','utf-8','gb18030','utf-16'].map(value=>({value,label:value}))" style="width:160px"/></n-form-item><n-form-item label="分隔符"><n-input v-model:value="form.delimiter" maxlength="1"/></n-form-item></n-space>
        <n-space v-if="form.format==='xlsx'"><n-form-item label="工作表（逗号分隔，空为全部）"><n-input v-model:value="form.sheets"/></n-form-item><n-form-item label="单元格范围（可选）"><n-input v-model:value="form.range" placeholder="A1:D1000"/></n-form-item></n-space>
        <n-form-item v-if="form.format==='json'" label="JSON 记录路径"><n-input v-model:value="form.recordsPath" placeholder="例如 data.items；根数组留空"/></n-form-item>
        <n-space><n-form-item label="应到时间"><n-input v-model:value="form.dueTime" placeholder="09:00"/></n-form-item><n-form-item label="交付延后天数"><n-input-number v-model:value="form.dueDayOffset" :min="0" :max="31"/></n-form-item></n-space><n-checkbox v-model:checked="form.allowEmpty">允许明确的空交付</n-checkbox><n-checkbox v-model:checked="form.allowContentRevision">允许内容更正产生新修订</n-checkbox>
      </template>
      <template v-if="kind==='REST_PULL'"><n-form-item label="接口路径"><n-input v-model:value="form.path" placeholder="/api/orders"/></n-form-item><n-form-item label="响应记录路径"><n-input v-model:value="form.apiRecordsPath" placeholder="例如 data.items"/></n-form-item><n-form-item label="分页方式"><n-select v-model:value="form.pagination" :options="['none','page','offset','next','token'].map(value=>({value,label:({none:'无分页',page:'页码',offset:'偏移量',next:'下一页链接',token:'游标'} as Record<string,string>)[value]}))"/></n-form-item><n-space><n-form-item label="每页记录数"><n-input-number v-model:value="form.pageSize" :min="1" :max="10000"/></n-form-item><n-form-item label="最大页数"><n-input-number v-model:value="form.maxPages" :min="1" :max="100000"/></n-form-item></n-space><n-form-item v-if="['next','token'].includes(form.pagination)" label="响应中的下一页链接或游标路径"><n-input v-model:value="form.nextPath"/></n-form-item><n-space><n-form-item label="业务成功字段路径（可选）"><n-input v-model:value="form.successPath"/></n-form-item><n-form-item label="期望值"><n-input v-model:value="form.successValue"/></n-form-item></n-space></template>
      <n-button type="primary" :loading="busy" :disabled="!kind" class="gap" @click="reviewChange">保存并测试发现</n-button>
    </template>
    <template v-else-if="step===2&&sqlMode"><sql-ingestion :project="project" :source="channel?.source_id||0" :can-activate="canActivate" @ready="sqlReady=$event"/><n-space class="gap"><n-button @click="step=1">修改来源模式</n-button><n-button type="primary" :disabled="!sqlReady" @click="step=3">设置交付计划</n-button></n-space></template>
    <template v-else-if="step===2"><n-tag>{{stateLabels[probe?.state||'']||'尚未测试'}}</n-tag><n-alert v-if="probe?.error_code" type="error" class="gap">{{probe.error_code}}</n-alert><p v-if="probe?.state==='COMPLETE'">{{kind==='MYSQL_SNAPSHOT'?`发现 ${probe.result?.tableCount} 张基础表`:kind==='FILE_SCAN'?`目录可读，发现 ${probe.result?.fileCount} 个结构化文件`:`首个响应通过，包含 ${probe.result?.firstPageRows} 条记录`}}</p><template v-if="kind==='MYSQL_SNAPSHOT'&&probe?.result?.inventory"><n-data-table :columns="[{title:'发现表',key:'table'},{title:'引擎',key:'engine'}]" :data="probe.result.inventory.tables" :pagination="{pageSize:25}"/><n-alert v-if="probe.result.unsupportedCount" type="warning">不支持对象 {{probe.result.unsupportedCount}} 个，需作为接入例外处理。</n-alert><pre v-if="probe.result.unsupportedCount" class="json-detail">{{JSON.stringify(probe.result.inventory.unsupported_objects,null,2)}}</pre></template><p class="muted">测试通过表示当前连接及发现成功，完整交付仍以执行批次为准。</p><n-space><n-button @click="editingChannel=true;step=1">修改采集规则</n-button><n-button @click="testConnection">重新测试</n-button><n-button type="primary" :disabled="probe?.state!=='COMPLETE'||!canActivate" @click="step=3">设置交付计划</n-button></n-space></template>
    <template v-else><n-form-item label="业务时区"><n-input value="Asia/Shanghai" readonly/></n-form-item><n-space><n-form-item label="开始日期"><n-input v-model:value="form.startDate" placeholder="YYYY-MM-DD"/></n-form-item><n-form-item label="每日执行时间"><n-input v-model:value="form.triggerTime" placeholder="08:00"/></n-form-item><n-form-item label="迟到等待天数"><n-input-number v-model:value="form.lateDays" :min="0" :max="31"/></n-form-item></n-space><n-checkbox v-if="kind!=='MYSQL_SNAPSHOT'" v-model:checked="form.historicalRead">已确认此来源可按业务日期读取历史交付</n-checkbox><n-alert type="info" class="gap">启用后由后台按计划运行。MySQL 当前态快照无法补造过去的数据。</n-alert><n-button type="primary" :loading="busy" @click="activate">确认范围并启用</n-button></template>
  </n-modal>
  <n-modal v-model:show="changeVisible" preset="card" title="确认采集规则变更" style="width:min(800px,95vw)"><n-alert v-if="error" type="error">{{error}}</n-alert><p>新规则需重新预检与启用计划，既有执行和历史交付约定继续保留。</p><pre class="json-detail">{{JSON.stringify({previous:channel?.config,proposed:settings(),connectionVersion:form.connectionVersion,impact:changeImpact},null,2)}}</pre><n-input v-model:value="changeReason" placeholder="范围或规则变更原因"/><n-button class="gap" type="primary" :disabled="!changeReason.trim()" :loading="busy" @click="changeVisible=false;create()">确认变更并测试</n-button></n-modal>
  <n-modal v-model:show="connectionVersionVisible" preset="card" title="连接版本与影响" style="width:min(800px,95vw)"><n-alert v-if="error" type="error">{{error}}</n-alert><p>当前版本 {{connection?.active_version}}。发布新版本后，各通道通过“修改采集规则”显式选择，正在执行的配置不会被改写。凭证由管理员在批准资源边界内轮换。</p><pre class="json-detail">{{JSON.stringify(changeImpact,null,2)}}</pre><n-form-item v-if="connection?.kind!=='MYSQL_SNAPSHOT'" label="连接说明"><n-input v-model:value="connectionDescription"/></n-form-item><n-form-item label="新版本原因"><n-input v-model:value="connectionReason"/></n-form-item><n-button type="primary" :disabled="!connectionReason.trim()" :loading="busy" @click="saveConnectionVersion">发布连接配置新版本</n-button></n-modal>
</template>
