<script setup lang="ts">
import { computed,defineAsyncComponent,h,ref,watch } from 'vue'
import { NAlert,NButton,NCard,NDataTable,NFormItem,NInput,NModal,NPagination,NSelect,NSpace,NTabPane,NTabs,NTag } from 'naive-ui'
import { api,type Page } from './api'
import type { PickedAsset } from './AssetPicker.vue'
const RefreshPanel=defineAsyncComponent(()=>import('./RefreshPanel.vue'))
const AssetPicker=defineAsyncComponent(()=>import('./AssetPicker.vue'))
const props=defineProps<{project:number;canManage:boolean}>()
interface Dataset{id:number;code:string;name:string;active_model_version:number;active_release_id:number|null}
interface Input{alias:string;sourceCode:string;objectName:string;columns:{name:string;type:string}[]}
interface Contract{inputs:Input[];grain:string;domain:string;fields:{name:string;type:string}[];qualityRules?:Record<string,unknown>[]}
interface Package{id:number;package_id:number;repository_code:string;project_path:string;git_revision:string;state:string;error_code:string;contract:Contract}
const q=ref(''),page=ref(1),total=ref(0),rows=ref<Dataset[]>([]),selected=ref<Dataset|null>(null),error=ref(''),busy=ref(false)
const versions=ref<{version:number;contract:Contract;git_revision:string;bundle_sha256:string}[]>([]),version=ref<number|null>(null),builds=ref<Record<string,any>[]>([]),releases=ref<Record<string,any>[]>([])
const bindings=ref<Record<string,PickedAsset>>({}),picker=ref(false),alias=ref(''),creating=ref(false),modelCode=ref(''),modelName=ref(''),chosenPackage=ref<Package|null>(null),importing=ref(false)
const repositories=ref<{code:string;name:string;project_paths:string[]}[]>([]),repository=ref<string|null>(null),projectPath=ref<string|null>(null),gitRef=ref('HEAD'),packages=ref<Package[]>([]),packagePage=ref(1),packageTotal=ref(0)
const contract=computed(()=>creating.value?chosenPackage.value?.contract:versions.value.find(v=>v.version===version.value)?.contract)
const wanted=computed(()=>contract.value?.inputs.find(i=>i.alias===alias.value))
const columns=[{title:'数据集',key:'name',render:(r:Dataset)=>h(NButton,{text:true,type:'primary',onClick:()=>inspect(r)},()=>r.name)},{title:'编码',key:'code'},{title:'模型版本',key:'active_model_version'},{title:'当前发布',key:'active_release_id'}]
const packageColumns=[{title:'Git 项目',key:'project_path'},{title:'状态',key:'state'},{title:'提交',key:'git_revision',render:(r:Package)=>r.git_revision?.slice(0,12)||r.error_code||'等待 Worker'},{title:'操作',key:'actions',render:(r:Package)=>h(NButton,{size:'small',disabled:r.state!=='COMPLETE',onClick:()=>{chosenPackage.value=r;creating.value=true;bindings.value={};modelCode.value=selected.value?.code||'';modelName.value=selected.value?.name||'';importing.value=false}},()=>selected.value?'用此包新增模型版本':'绑定资产建立模型')}]
const buildColumns=[{title:'构建',key:'id'},{title:'模型版本',key:'model_version'},{title:'状态',key:'state'},{title:'原因',key:'error_code'},{title:'操作',key:'actions',render:(r:Record<string,any>)=>h(NSpace,{},()=>[h(NButton,{size:'small',onClick:()=>{buildDetail.value=r;detailVisible.value=true}},()=> '质量与依赖'),...(r.state==='READY'&&props.canManage?[h(NButton,{size:'small',onClick:()=>{publishBuild.value=r.id;publishReason.value='';publishVisible.value=true}},()=> '发布')]:[]),...(['QUEUED','RUNNING'].includes(r.state)?[h(NButton,{size:'small',onClick:()=>cancel(r.id)},()=> '取消')]:[])])}]
const buildDetail=ref<Record<string,any>|null>(null),detailVisible=ref(false),publishBuild=ref<number|null>(null),publishVisible=ref(false),publishReason=ref('')
let generation=0
async function load(){const current=++generation;busy.value=true;error.value='';try{const result=await api<Page<Dataset>>(`/warehouse/catalog/projects/${props.project}/models?q=${encodeURIComponent(q.value)}&limit=25&offset=${(page.value-1)*25}`);if(current===generation){rows.value=result.items;total.value=result.total}}catch(e){if(current===generation)error.value=(e as Error).message}finally{if(current===generation)busy.value=false}}
const route=()=>`/warehouse/projects/${props.project}/datasets/${selected.value?.id}`
async function inspect(row:Dataset){selected.value=row;bindings.value={};try{await refresh();version.value=versions.value[0]?.version||null}catch(e){error.value=(e as Error).message}}
async function refresh(){if(!selected.value)return;[versions.value,builds.value,releases.value]=await Promise.all([api<typeof versions.value>(route()+'/versions'),api<Record<string,any>[]>(route()+'/builds'),api<Record<string,any>[]>(route()+'/releases')]);selected.value={...selected.value,active_model_version:versions.value[0]?.version||0,active_release_id:releases.value[0]?.id||null}}
async function loadPackages(){const result=await api<Page<Package>>(`/warehouse/projects/${props.project}/model-packages?limit=25&offset=${(packagePage.value-1)*25}`);packages.value=result.items;packageTotal.value=result.total}
async function openImport(){busy.value=true;error.value='';try{repositories.value=await api(`/warehouse/projects/${props.project}/model-repositories`);repository.value=repositories.value[0]?.code||null;packagePage.value=1;await loadPackages();importing.value=true}catch(e){error.value=(e as Error).message}finally{busy.value=false}}
async function importPackage(){busy.value=true;error.value='';try{await api(`/warehouse/projects/${props.project}/model-packages`,{repository:repository.value,projectPath:projectPath.value,revision:gitRef.value,requestKey:crypto.randomUUID()});await loadPackages()}catch(e){error.value=(e as Error).message}finally{busy.value=false}}
function choose(value:PickedAsset){bindings.value[alias.value]=value;picker.value=false}
async function saveModel(){busy.value=true;error.value='';try{const result=await api<{id:number;version:number}>(`/warehouse/projects/${props.project}/models`,{code:modelCode.value,name:modelName.value,expectedVersion:selected.value?.active_model_version||0,packageId:chosenPackage.value?.package_id,bindings:Object.fromEntries(Object.entries(bindings.value).map(([a,v])=>[a,{sourceCode:v.source_code,objectName:v.name}]))});creating.value=false;const keep={...bindings.value};await load();await inspect({id:result.id,code:modelCode.value,name:modelName.value,active_model_version:result.version,active_release_id:selected.value?.active_release_id||null});bindings.value=keep}catch(e){error.value=(e as Error).message}finally{busy.value=false}}
async function build(){busy.value=true;error.value='';try{await api(route()+'/builds',{requestKey:crypto.randomUUID(),modelVersion:version.value,inputs:Object.fromEntries(Object.entries(bindings.value).map(([a,v])=>[a,v.id]))});await refresh()}catch(e){error.value=(e as Error).message}finally{busy.value=false}}
async function cancel(id:number){try{await api(route()+`/builds/${id}/cancel`,{});await refresh()}catch(e){error.value=(e as Error).message}}
async function publish(){busy.value=true;error.value='';try{await api(route()+`/builds/${publishBuild.value}/publish`,{reason:publishReason.value});publishVisible.value=false;await refresh()}catch(e){error.value=(e as Error).message}finally{busy.value=false}}
watch(repository,()=>{projectPath.value=repositories.value.find(r=>r.code===repository.value)?.project_paths[0]||null});watch(packagePage,()=>loadPackages().catch(e=>error.value=e.message));watch(version,()=>bindings.value={});watch(page,()=>void load());watch(()=>props.project,()=>{selected.value=null;creating.value=false;page.value=1;void load()},{immediate:true})
</script>
<template>
  <n-alert v-if="error" type="error" class="gap">{{error}}</n-alert>
  <n-card v-if="!selected" title="数据开发"><template #header-extra><n-button type="primary" @click="openImport">从 Git 模型包建立数据集</n-button></template><n-space class="gap"><n-input v-model:value="q" placeholder="数据集名称" @keyup.enter="page=1;load()"/><n-button @click="page=1;load()">搜索</n-button></n-space><n-data-table :columns="columns" :data="rows" :loading="busy"/><n-pagination v-model:page="page" :item-count="total" :page-size="25" class="gap"/></n-card>
  <template v-else><n-space class="gap"><n-button @click="selected=null;load()">返回数据集目录</n-button><n-button @click="refresh().catch(e=>error=e.message)">刷新状态</n-button><n-button @click="openImport">登记模型新版本</n-button></n-space><n-card :title="selected.name"><n-space align="center"><n-select v-model:value="version" :options="versions.map(v=>({label:`模型版本 ${v.version}`,value:v.version}))" style="width:180px"/><n-tag>当前发布 {{selected.active_release_id||'尚未发布'}}</n-tag></n-space><p>粒度：{{contract?.grain}} · 业务域：{{contract?.domain}}</p><h3>选择本次构建的输入版本</h3><n-space v-for="input in contract?.inputs" :key="input.alias" class="gap" align="center"><strong>{{input.alias}}</strong><span>{{input.sourceCode}} / {{input.objectName}}</span><n-button @click="alias=input.alias;picker=true">选择资产版本</n-button><span v-if="bindings[input.alias]">{{bindings[input.alias].data_window}} · 批次 {{bindings[input.alias].run_id}}</span></n-space><n-button type="primary" class="gap" :loading="busy" :disabled="Object.keys(bindings).length!==contract?.inputs.length" @click="build">使用固定输入构建</n-button><n-data-table :columns="buildColumns" :data="builds" class="gap"/><p class="muted">展示最近 200 次构建。每次构建和发布保留固定模型、输入与质量结果。</p><RefreshPanel v-if="version&&contract" :project="project" :dataset="selected.id" :model-version="version" :inputs="contract.inputs" :can-manage="canManage"/></n-card></template>
  <n-modal v-model:show="importing" preset="card" title="登记 Git 模型包" style="width:min(980px,96vw)"><n-alert v-if="error" type="error" class="gap">{{error}}</n-alert><p>选择管理员批准的 Git 项目；Worker 只打包已提交内容，保存固定提交和摘要。</p><n-space><n-form-item label="批准仓库"><n-select v-model:value="repository" :options="repositories.map(r=>({label:r.name,value:r.code}))" style="width:220px"/></n-form-item><n-form-item label="模型目录"><n-select v-model:value="projectPath" :options="(repositories.find(r=>r.code===repository)?.project_paths||[]).map(value=>({label:value,value}))" style="width:220px"/></n-form-item><n-form-item label="Git 分支、标签或提交"><n-input v-model:value="gitRef"/></n-form-item></n-space><n-space class="gap"><n-button type="primary" :loading="busy" :disabled="!repository||!projectPath" @click="importPackage">提交打包任务</n-button><n-button @click="loadPackages().catch(e=>error=e.message)">刷新包列表</n-button></n-space><n-data-table :columns="packageColumns" :data="packages"/><n-pagination v-model:page="packagePage" :item-count="packageTotal" :page-size="25" class="gap"/></n-modal>
  <n-modal v-model:show="creating" preset="card" title="绑定模型与项目资产" style="width:min(850px,96vw)"><n-alert v-if="error" type="error" class="gap">{{error}}</n-alert><n-space><n-form-item label="数据集编码"><n-input v-model:value="modelCode" :disabled="!!selected"/></n-form-item><n-form-item label="数据集名称"><n-input v-model:value="modelName"/></n-form-item></n-space><p>模型版本来自提交 {{chosenPackage?.git_revision}}，字段、粒度与质量规则由该版本定义。</p><n-space v-for="input in chosenPackage?.contract.inputs" :key="input.alias" class="gap" align="center"><strong>{{input.alias}}</strong><span>需要字段 {{input.columns.map(c=>c.name).join('、')}}</span><n-button @click="alias=input.alias;picker=true">选择来源对象</n-button><span>{{bindings[input.alias]?.source_code}} / {{bindings[input.alias]?.name}}</span></n-space><n-button type="primary" :loading="busy" :disabled="Object.keys(bindings).length!==chosenPackage?.contract.inputs.length" @click="saveModel">保存模型版本</n-button></n-modal>
  <n-modal v-model:show="picker" preset="card" title="选择完整资产版本" style="width:min(1080px,96vw)"><AssetPicker :project="project" :source="creating?undefined:wanted?.sourceCode" :object="creating?undefined:wanted?.objectName" @select="choose"/></n-modal>
  <n-modal v-model:show="detailVisible" preset="card" title="构建质量与依赖" style="width:min(980px,96vw)"><n-tabs><n-tab-pane name="quality" tab="质量检查"><n-alert v-if="!buildDetail?.result?.rulesConfigured" type="info">扩展质量规则尚未配置，基础结构、唯一性和必填检查仍执行。</n-alert><pre class="json-detail">{{JSON.stringify(buildDetail?.result,null,2)}}</pre></n-tab-pane><n-tab-pane name="lineage" tab="节点依赖"><n-data-table :columns="[{title:'节点',key:'id'},{title:'依赖',key:'dependsOn',render:(r:any)=>r.dependsOn.join(' → ')}]" :data="buildDetail?.result?.worker?.lineage||[]"/><p v-if="!buildDetail?.result?.worker?.lineage?.length">尚未取得 dbt 节点依赖；动态 SQL 的列级依赖未解析。</p></n-tab-pane><n-tab-pane name="inputs" tab="输入版本"><pre class="json-detail">{{JSON.stringify(buildDetail?.watermark,null,2)}}</pre></n-tab-pane></n-tabs></n-modal>
  <n-modal v-model:show="publishVisible" preset="card" title="发布已验证候选" style="width:min(620px,94vw)"><n-alert v-if="error" type="error" class="gap">{{error}}</n-alert><p>发布前再次检查当前版本、输入新旧、来源状态和数据权限。</p><n-form-item label="发布原因"><n-input v-model:value="publishReason"/></n-form-item><n-button type="primary" :loading="busy" :disabled="!publishReason.trim()" @click="publish">确认发布</n-button></n-modal>
</template>
