<script setup lang="ts">
import { h,reactive,ref,watch } from 'vue'
import { NAlert,NButton,NCard,NDataTable,NFormItem,NInput,NInputNumber,NModal,NPagination,NSelect,NSpace,NTag } from 'naive-ui'
import { api,type Page } from './api'
const props=defineProps<{project:number;dataset:number;modelVersion:number;inputs:{alias:string;sourceCode:string;objectName:string}[];canManage:boolean}>()
const day=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Shanghai'}).format(new Date())
const plan=ref<Record<string,any>|null>(null),windows=ref<Record<string,any>[]>([]),total=ref(0),page=ref(1),show=ref(false),error=ref(''),busy=ref(false),members=ref<{identity_id:string;role:string}[]>([]),detail=ref<Record<string,any>|null>(null),detailVisible=ref(false),reason=ref(''),targetDay=ref(day())
const form=reactive({serviceIdentity:'',publishMode:'MANUAL',latePolicy:'CONTINUE',timezone:'Asia/Shanghai',startDate:day(),triggerTime:'09:00',deadline:'10:00',maxSkewSeconds:86400,freshnessSeconds:172800,daysOfWeek:[1,2,3,4,5,6,7],inputSelectors:{} as Record<string,{businessDayOffset:number}>})
const names:Record<string,string>={WAITING_INPUTS:'等待必需输入',BUILDING:'构建中',READY_TO_PUBLISH:'等待负责人发布',PUBLISHED:'已发布',QUALITY_REJECTED:'质量检查未通过',NEEDS_ATTENTION:'需要处理',FAILED:'失败',CANCELLED:'已取消'}
const columns=[{title:'业务日期',key:'business_date'},{title:'计划版本',key:'plan_version'},{title:'状态',key:'state',render:(r:any)=>names[r.state]||r.state},{title:'原因',key:'reason'},{title:'发布',key:'release_id'},{title:'明细',key:'details',render:(r:any)=>h(NButton,{text:true,onClick:()=>{detail.value=r;detailVisible.value=true}},()=> '输入与缺项')}]
const route=()=>`/warehouse/projects/${props.project}/datasets/${props.dataset}/refresh`
let generation=0
async function retry(window:Record<string,any>){busy.value=true;error.value='';try{await api(route()+`/windows/${window.id}/retry`,{expectedBuildId:window.build_id,reason:reason.value});detailVisible.value=false;await load()}catch(e){error.value=(e as Error).message}finally{busy.value=false}}
async function load(){const current=++generation;error.value='';try{const [p,w]=await Promise.all([api<Record<string,any>>(route()),api<Page<Record<string,any>>>(route()+`/windows?limit=25&offset=${(page.value-1)*25}`)]);if(current===generation){plan.value=p;windows.value=w.items;total.value=w.total}}catch(e){if(current===generation)error.value=(e as Error).message}}
async function configure(){busy.value=true;error.value='';try{members.value=await api(`/warehouse/projects/${props.project}/members`);const p=plan.value;Object.assign(form,{serviceIdentity:p?.service_identity||'',publishMode:p?.config?.publishMode||'MANUAL',latePolicy:p?.config?.latePolicy||'CONTINUE',timezone:p?.config?.timezone||'Asia/Shanghai',startDate:p?.config?.startDate||day(),triggerTime:p?.config?.triggerTime||'09:00',deadline:p?.config?.deadline||'10:00',maxSkewSeconds:p?.config?.maxSkewSeconds??86400,freshnessSeconds:p?.config?.freshnessSeconds??172800,daysOfWeek:p?.config?.daysOfWeek||[1,2,3,4,5,6,7],inputSelectors:Object.fromEntries(props.inputs.map(i=>[i.alias,{businessDayOffset:p?.config?.inputSelectors?.find((s:any)=>s.alias===i.alias)?.businessDayOffset||0}]))});show.value=true}catch(e){error.value=(e as Error).message}finally{busy.value=false}}
async function save(){busy.value=true;error.value='';try{await api(route(),{...form,expectedVersion:plan.value?.active_version||0,modelVersion:props.modelVersion});show.value=false;await load()}catch(e){error.value=(e as Error).message}finally{busy.value=false}}
async function reconcile(approveLate=false){busy.value=true;error.value='';try{await api(route()+'/reconcile',{day:targetDay.value,approveLate,reason:reason.value});await load()}catch(e){error.value=(e as Error).message}finally{busy.value=false}}
async function toggle(){busy.value=true;error.value='';try{await api(route()+'/state',{state:plan.value?.state==='ACTIVE'?'PAUSED':'ACTIVE',expectedRevision:plan.value?.revision,reason:reason.value});await load()}catch(e){error.value=(e as Error).message}finally{busy.value=false}}
watch(()=>[props.project,props.dataset],()=>{page.value=1;void load()},{immediate:true});watch(page,()=>void load())
</script>
<template>
  <n-card title="每日数据集刷新" class="gap"><template #header-extra><n-button v-if="canManage" @click="configure">{{plan?.configured?'修改刷新计划':'配置刷新计划'}}</n-button></template>
    <n-alert v-if="error" type="error" class="gap">{{error}}</n-alert><p v-if="!plan?.configured">尚未配置自动刷新。先发布经验证的模型，再选择项目服务身份和每日输入规则。</p>
    <template v-else><n-space><n-tag>{{plan.state==='ACTIVE'?'计划启用':'计划暂停'}}</n-tag><n-tag>{{plan.config.publishMode==='AUTO'?'已批准自动发布':'人工发布'}}</n-tag><span>{{plan.config.timezone}} · {{plan.config.triggerTime}} · 服务身份 {{plan.service_identity}}</span></n-space><n-space v-if="canManage" class="gap"><n-input v-model:value="targetDay" placeholder="业务日期 YYYY-MM-DD" style="width:160px"/><n-button :loading="busy" @click="reconcile()">检查输入并推进</n-button><n-input v-model:value="reason" placeholder="暂停 / 恢复 / 迟到批准原因" style="width:240px"/><n-button :disabled="!reason.trim()" @click="toggle">{{plan.state==='ACTIVE'?'暂停计划':'恢复计划'}}</n-button><n-button :disabled="!reason.trim()" @click="reconcile(true)">批准该日迟到补算</n-button></n-space><n-data-table :columns="columns" :data="windows"/><n-pagination v-model:page="page" :item-count="total" :page-size="25" class="gap"/></template>
  </n-card>
  <n-modal v-model:show="show" preset="card" title="每日刷新计划" style="width:min(850px,96vw)"><n-alert v-if="error" type="error" class="gap">{{error}}</n-alert><n-form-item label="项目服务身份"><n-select v-model:value="form.serviceIdentity" :options="members.filter(m=>['OWNER','ENGINEER'].includes(m.role)).map(m=>({label:`${m.identity_id} · ${m.role}`,value:m.identity_id}))" placeholder="先在项目设置建立独立服务身份"/></n-form-item><n-space><n-form-item label="发布策略"><n-select v-model:value="form.publishMode" :options="[{label:'人工确认发布',value:'MANUAL'},{label:'已批准模型自动发布',value:'AUTO'}]" style="width:230px"/></n-form-item><n-form-item label="迟到处理"><n-select v-model:value="form.latePolicy" :options="[{label:'继续等待并使用更正版本',value:'CONTINUE'},{label:'超过截止后人工批准',value:'MANUAL'}]" style="width:260px"/></n-form-item></n-space><n-alert type="info" class="gap">自动发布要求本模型版本已有人工发布，服务身份具有负责人权限；模型、输入或授权变化会再次检查。</n-alert><n-space><n-form-item label="业务时区"><n-input v-model:value="form.timezone"/></n-form-item><n-form-item label="开始日期"><n-input v-model:value="form.startDate"/></n-form-item><n-form-item label="检查时间"><n-input v-model:value="form.triggerTime"/></n-form-item><n-form-item label="应到截止"><n-input v-model:value="form.deadline"/></n-form-item></n-space><n-form-item label="执行日"><n-select v-model:value="form.daysOfWeek" multiple :options="['周一','周二','周三','周四','周五','周六','周日'].map((label,i)=>({label,value:i+1}))"/></n-form-item><n-space><n-form-item label="跨来源最大采集时差（秒）"><n-input-number v-model:value="form.maxSkewSeconds" :min="0" :max="2678400"/></n-form-item><n-form-item label="数据新鲜度要求（秒）"><n-input-number v-model:value="form.freshnessSeconds" :min="60" :max="31536000"/></n-form-item></n-space><n-space v-for="input in inputs" :key="input.alias" align="center" class="gap"><span>{{input.alias}} · {{input.sourceCode}} / {{input.objectName}}</span><n-select v-if="form.inputSelectors[input.alias]" v-model:value="form.inputSelectors[input.alias].businessDayOffset" :options="[{label:'相同业务日',value:0},...Array.from({length:31},(_,i)=>({label:`前 ${i+1} 个业务日`,value:-(i+1)}))]" style="width:180px"/></n-space><n-button type="primary" :loading="busy" @click="save">保存并启用此版本</n-button></n-modal>
  <n-modal v-model:show="detailVisible" preset="card" title="刷新窗口详情" style="width:min(880px,96vw)"><n-alert v-if="error" type="error" class="gap">{{error}}</n-alert><template v-if="detail&&canManage&&['FAILED','CANCELLED'].includes(detail.state)"><p>重试保留本次固定输入与模型版本；旧构建及失败记录继续保留。</p><n-input v-model:value="reason" placeholder="重试原因"/><n-button :disabled="!reason.trim()" :loading="busy" class="gap" @click="retry(detail)">使用相同输入重试</n-button></template><pre class="json-detail">{{JSON.stringify(detail,null,2)}}</pre></n-modal>
</template>
